"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const car_1 = require("./car");
const vehicle_1 = require("./vehicle");
var c = new car_1.Car();
c.turnLeft();
c.openHood();
c.turnRight();
var d = new vehicle_1.Vehicle();
d.turnLeft();
d.turnRight();
